name: Deployment

on:
  push:
    tags:
     - 'v*'

jobs:

  pypi:
    name: Build and push Python package
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install pypa/build
      run: |
        python -m pip install build --user
    - name: Build a binary wheel and a source tarball
      run: |
        python -m build --sdist --wheel --outdir dist/ .

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.10

